os: osx

jobs:
  include:
    - stage: Run Sylph on AWS Device Farms
      env: Run Sylph on AWS Device Farms
      before_install:

      # install aws
      - curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
      - unzip awscli-bundle.zip
      - sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
      - aws --version
      - mkdir ~/.aws || echo "problem creating dir"
      - |
        cat >> ~/.aws/config <<EOL
        [default]
        output = json
        region = us-west-2
        EOL
      - cat ~/.aws/config
      - cat pubspec.yaml
      - aws devicefarm list-projects

      # Install android tools
      - ANDROID_TOOLS=4333796 # android-28
      - export ANDROID_HOME=~/android-sdk
      - wget -q "https://dl.google.com/android/repository/sdk-tools-darwin-$ANDROID_TOOLS.zip" -O android-sdk-tools.zip
      - unzip -q android-sdk-tools.zip -d ${ANDROID_HOME}
      - rm android-sdk-tools.zip
      - PATH=${PATH}:${ANDROID_HOME}/emulator:${ANDROID_HOME}/tools/bin:${ANDROID_HOME}/platform-tools
      # Silence warning.
      - mkdir -p ~/.android
      - touch ~/.android/repositories.cfg
#      # install correct version of java on osx
#      - export HOMEBREW_NO_AUTO_UPDATE=1
#      - brew cask uninstall java; brew tap caskroom/versions; brew cask install java8;
      # Accept licenses before installing components, no need to echo y for each component
      - yes | sdkmanager --licenses
      # Platform tools
      - sdkmanager "emulator" "tools" "platform-tools" > /dev/null
      - sdkmanager --list | head -15

      # fix timezone warning on osx
      - sudo ln -sf /usr/share/zoneinfo/US/Pacific /etc/localtime

      # setup osx environment for flutter and simulators
      - export HOMEBREW_NO_AUTO_UPDATE=1
      - brew install libimobiledevice
      - brew install ideviceinstaller
      - brew install ios-deploy
      - brew install cocoapods || echo 'ignore exit(1)'
      - brew link --overwrite cocoapods

      # install pre-compiled flutter
      - FLUTTER_CHANNEL=stable
      - FLUTTER_VERSION=1.2.1-${FLUTTER_CHANNEL}
      - wget --quiet --output-document=flutter.zip https://storage.googleapis.com/flutter_infra/releases/${FLUTTER_CHANNEL}/macos/flutter_macos_v${FLUTTER_VERSION}.zip && unzip -qq flutter.zip > /dev/null && rm flutter.zip
      - export PATH="$PATH":"$HOME/.pub-cache/bin"
      - export PATH=$PWD/flutter/bin:$PWD/flutter/bin/cache/dart-sdk/bin:$PATH
      - flutter doctor -v

      # install most current (released or unreleased) version of Sylph
      - pub global activate --source path .

      script:
      - cd example; sylph

#      # copy artifacts to cache for later deploy
#      - tar cvzf $HOME/screenshots/screenshots.tar.gz ios/fastlane/screenshots android/fastlane/metadata/android/*/images
#      - zip -r $HOME/screenshots/screenshots.zip ios/fastlane/screenshots android/fastlane/metadata/android/*/images
#      # save artifacts for later deploy of second artifact
#      cache:
#        directories:
#          - $HOME/screenshots
#
#      # deploy artifacts
#      deploy:
#        provider: releases
#        draft: false
#        skip_cleanup: true
#        api_key:
#          secure: wyPNNbjTFChWOGc/JiTpGhN490dRzz/qhU2T3CddZALjy4VN3LywennK3xnTOAq+FEYE9H/quP/SxkUX154al/lxeL6QuN5D0Ev2bL3lS9jyaoe0NOKx5GnNTzfv84taZPi768UF4rgYqzzdF8WJTCe0dlvDH7qKgH+dHIZGoB1dM/hhWMEXUv0uAZuFDkepxWHOLHsIABunkz428MEsSRCTdEWOsgdFiEl+DOC5ErmorgHazUWPpSwenz13kCLhU+wT2Fsek5tGBO6GT1Mvw8qrht3LUZBaBQJfx4yhdXQKtq0Dr+gI9a3sbF/3TKV0nRvDVA+KGmMLHT+fkRrz1xkGvrLnCDfkylDZlmn/IoQUkv4JwI+lJIXfUp40pMmSlFH1WKToWSjMsPSxv02fVYzxNZoxlno+qyKk4lfdROOSSYS5LjmMd+Lrvhmx7vNMCHl57fdXdKwgyJllxT/khMZTJv5IPQih1yi3m/hDw0s59IHYd22QHFoodcdAPy2xxeVh8VhzhucpesWAvoFZfgdTmPZXAzpMR4kEaeBb5f3Z/Eg3AypDPXg67kXwFqTRL+ZqDzOFynZYJML8RbsZd/nqU5TYc0Ocmh0YMA3v0Z43wuZMshXOXujl8z3zmnwzV/QmFP0U/phOGa9SmvKtRyGQoTGtIXoPWdXrRpgm3F4=
#        file: $HOME/sylph/sylph.tar.gz
#        on:
#          tags: true
